## Understanding NumPy basics
## Date: 21/1/22

In [2]:
import numpy as np

In [2]:
#Creating a simple 1D array
x = np.array([1, 0, 4, 3, 7, 5])
x

array([1, 0, 4, 3, 7, 5])

In [3]:
#Assessing array elements
l = len(x)
x[:l-1]
x[2:4]

array([4, 3])

In [5]:
#multi index that return an array instead of a single numeric
x[[0, 1, 4]]

array([1, 0, 7])

In [15]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [16]:
a

array([0, 1, 2, 3, 4])

In [6]:
#Boolean array
x <= 2

array([ True,  True, False, False, False, False])

In [7]:
#provide condition as the index. This will return the elements that hold true for the condition rather than the boolean array itself
x[x<=2]

array([1, 0])

In [9]:
#return mean of array
y = x.mean()
y

3.3333333333333335

In [10]:
#use index to filter out elements of array that are larger than the mean value
x[x > y]

array([4, 7, 5])

In [11]:
x[x < y]

array([1, 0, 3])

In [12]:
x.std()

2.357022603955158

In [22]:
#combine conditions with and 
x[(x > 2) & (x %2 == 0)]

array([4])

## Exercises
## Date: 25/1/22

In [10]:
# Create a numpy array of size 10, filled with zeros.
a = np.array([0] * 10)
print(a)
# or
b = np.zeros(10)
print(b)

[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
# Create a numpy array with values ranging from 10 to 49
a = np.array(range(10, 50))
print(a)
#this is a better way
x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
#  Create a numpy matrix of 2*2 integers, filled with ones.
A = np.ones([2,2], dtype= np.int)
print(A)

[[1 1]
 [1 1]]


C:\Users\user\AppData\Local\Temp/ipykernel_16844/4050638351.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.ones([2,2], dtype= np.int)


In [20]:
#  Create a numpy array, filled with 3 random integer values between 1 and 10.
np.random.randint(10, size=3)

array([6, 8, 3])

In [22]:
#Given the X python list convert it to an Y numpy array
# your code goes here
X = [1, 2, 3]
print(X, type(X))
Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [25]:
#Boolean arrays (also called masks)
#Given the X numpy array, make a mask showing negative elements
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
X < 0

array([ True, False, False,  True, False, False, False, False,  True,
       False])

In [26]:
#Given the X numpy array, get the negative elements
X[X < 0]

array([-1, -4, -9])